name: gsy-framework-ci
on:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        TOXENV: ci
        GITHUB_ACCESS_TOKEN: ${{ secrets.GSYDEV_TOKEN }}
        TARGET_BRANCH: ${{ github.ref }}
      run: |
        pip install tox==3.24.4
        tox -e $TOXENV

    - name: Check coverage with Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN_GSY_FRAMEWORK }}
        fail_ci_if_error: true
        verbose: true
